-- Create collection table if it doesn't exist
CREATE TABLE IF NOT EXISTS collection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  title TEXT NOT NULL,
  summary TEXT,
  topic TEXT,
  source TEXT,
  url TEXT NOT NULL,
  UID UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Create index for faster user lookups
CREATE INDEX IF NOT EXISTS collection_uid_idx ON collection(UID);

-- Enable RLS
ALTER TABLE collection ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Allow users to read all bookmarks
CREATE POLICY "Collection items are viewable by everyone" ON collection
  FOR SELECT USING (true);

-- Allow users to insert their own bookmarks
CREATE POLICY "Users can insert their own collection items" ON collection
  FOR INSERT WITH CHECK (auth.uid() = UID);

-- Allow users to update their own bookmarks
CREATE POLICY "Users can update their own collection items" ON collection
  FOR UPDATE USING (auth.uid() = UID);

-- Allow users to delete their own bookmarks
CREATE POLICY "Users can delete their own collection items" ON collection
  FOR DELETE USING (auth.uid() = UID); 